version: '3'

services:
  haproxy:
    image: "haproxy"
    ports:
     - '80:8080'
    volumes:
     - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  nginx1:
    image: "nginx"
    volumes:
     - ./nginx/html/nginx_pages_server1:/usr/share/nginx/html
    ports:
     - "3000:80"


  nginx2:
    image: "nginx"
    volumes:
     - ./nginx/html/nginx_pages_server2:/usr/share/nginx/html
    ports:
     - "4000:80"
